### ISSUE TITLE
Document the test suite with probability of failure

### ISSUE THREAD

**Issue by dtolnay** [tkaitchuck/constrandom#10]
It looks like the tests in tests.rs are intentionally flaky. Any of the three below assertions could fail nondeterministically. Usually this is frowned upon. In this case the probabilities are so low that it's unlikely to ever be observed, but it would be helpful to acknowledge this with a comment that documents the probability of failure.

https://github.com/tkaitchuck/constrandom/blob/3425388e7fd027c21e3ac7fcffc8c1ea3e9b0e32/tests/tests.rs#L5-L9

**Comment by tkaitchuck** [comment]
Fixed: https://github.com/tkaitchuck/constrandom/commit/56ae149f5cb559b45bbb2c1ca321aa1eebdec48e
