### ISSUE TITLE
Usize support

### ISSUE THREAD

**Issue by dtolnay** [tkaitchuck/constrandom#14]
`const_random!(usize)` and `const_random!(isize)` are not currently supported. This is likely because the proc macro runs on the host and may have a different usize size than the target.

One approach that would work for implementing these is to expand to an `as` cast:

```rust
const_random!(usize)

// expands to:
const_random!(u128) as usize
```

which will truncate high bits and produce a correctly usize-sized random value.

**Comment by tkaitchuck** [comment]
Done https://github.com/tkaitchuck/constrandom/commit/d6982324dec0181bad039e9bdd0955544b2330ad
