### ISSUE TITLE
Release 0.1.10 breaks support for stable toolchain

### ISSUE THREAD

**Issue by akien-mga** [tkaitchuck/constrandom#17]
Compiling [bevy](https://crates.io/crates/bevy) which uses your crate, I run into an error with stable Rust (1.46.0) since the release of 0.1.10 on crates.io:
```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /home/akien/.cargo/registry/src/github.com-1ecc6299db9ec823/const-random-macro-0.1.10/src/lib.rs:1:1
  |
1 | #![feature(proc_macro_quote)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Pinning to 0.1.8 fixes it.

*Edit:* I know that using the nightly toolchain would fix it, but I'm reporting this in case you didn't intend to make `const-random-macro` a nightly-only crate.

**Comment by dvdplm** [comment]
Also breaks e.g. https://github.com/jonhoo/inferno

**Comment by reyk** [comment]
And ahash, hashbrown and many other crates that depend on it indirectly.

**Comment by ShaleXIONG** [comment]
I have the same problem under  nightly-2020-05-07

**Comment by vmx** [comment]
In case you are blocked by this while developing, you can use my branch for now until this is resolved (in whichever way). Just patch the dependency in the root `Cargo.toml` of your project like this:

```toml
[patch.crates-io]
const-random-macro = { git = "https://github.com/vmx/constrandom", branch = "back-to-stable" }
```

**Comment by Ten0** [comment]
Shouldn't 0.1.10 be yanked because of this?

**Comment by tkaitchuck** [comment]
@Ten0 It has been.
