### ISSUE TITLE
once_cell requires default-features = false for no-std

### ISSUE THREAD

**Issue by schungx** [tkaitchuck/constrandom#25]
The dependency on `once_cell` is pulling in `std`... which makes build fail on `no-std`.

Probably needs `default-features = false`.

**Comment by notgull** [comment]
Since this is a macro dependency, wouldn't it not actually need `once_cell` in the final binary? Or is this just a rustc/cargo bug?

**Comment by tkaitchuck** [comment]
@schungx I have removed the unneeded features. But I believe @notgull is correct, const_random should be used as a dev dependency. You don't need it as a normal dependency so std should not affect the project using it.

**Comment by schungx** [comment]
Version `0.13.0` worked fine, and `once_cell` was introduced after that.

I originally thought that macros was separate from the main compile, but it looks like cargo will still merge features from macros into the final features set for the build.
