### ISSUE TITLE
Build without `getrandom`

### ISSUE THREAD

**Issue by vbrandl** [tkaitchuck/constrandom#3]
Is it possible to build this crate with glibc < 2.29 (without `getrandom()`)?

**Comment by tkaitchuck** [comment]
@vbrandl Do you have a suggestion for a source of randomness?
I could add a feature to switch it if there was another path available.

**Comment by Amanieu** [comment]
I think this is not an issue. The `getrandom` crate should work fine on systems without `getrandom`, it will just fall back down to reading from /dev/urandom.

**Comment by vbrandl** [comment]
Yeah seems like this was a problem on my site, due to conflicting versions of libc (2.30 from my Arch Linux and 2.26 at the time from the nix package manager). nix-unstable updated to 2.27 and the compilation error disappeared.
