### ISSUE TITLE
no_std usage broken

### ISSUE THREAD

**Issue by sleffler** [tkaitchuck/constrandom#32]
Commit [4ef07e25a8b08153d527db84dd7f02d398ea1040](https://github.com/tkaitchuck/constrandom/commit/4ef07e25a8b08153d527db84dd7f02d398ea1040) broke no_std support. This in turn broke my no_std usage of the hashbrown crate because I use ahash with the compile-time-rng feature which brings in const-random. (ahash pins const-random to 0.1.12 but because the maintainers yanked that version it appears the dep floats to the latest rev.)

**Comment by tkaitchuck** [comment]
Fixed in 0.1.17
