### ISSUE TITLE
Include LICENSE files

### ISSUE THREAD

**Issue by ignatenkobrain** [tkaitchuck/constrandom#4]
It would be very awesome if you could include LICENSE-MIT and LICENSE-APACHE files and make a new release.

Having text of full license is mandatory by the license terms.

Thanks!

**Comment by ignatenkobrain** [comment]
Also please put it into a macro directory so that macro subcrate would get them on crates.io. Or if you don't care about publishing from windows, 'you can make a symlink.

**Comment by tkaitchuck** [comment]
Done. Version: 0.1.8
